### ISSUE TITLE
Checklist for Milestone 1

### ISSUE THREAD

**Issue by Prabh95** [UBC-MDS/DSCI-532_2024_21_Job-Postings#5]
- [x] Team Work Contract
- [x] Proposal Section 1
- [x] Proposal Section 2
- [x] Proposal Section 3
- [x] Proposal Section 4
- [x] Respository Structure
- [x] Use Github issues for discussion
- [x] Challenging: Start developing your app

**Comment by Owl64901** [comment]
Milestone 1 Checklist Completed!
